"""set column name

Revision ID: 295195b72d25
Revises: 5128fccc8d4d
Create Date: 2024-01-13 17:31:24.907669

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "295195b72d25"
down_revision: Union[str, None] = "5128fccc8d4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "categories", ["id"])
    op.add_column("movies", sa.Column("rating", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "movies", ["id"])
    op.drop_column("movies", "raiting")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies",
        sa.Column("raiting", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "movies", type_="unique")
    op.drop_column("movies", "rating")
    op.drop_constraint(None, "categories", type_="unique")
    # ### end Alembic commands ###
