"""change movie model

Revision ID: 4eea97ef1676
Revises: 295195b72d25
Create Date: 2024-01-13 23:48:13.886722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eea97ef1676'
down_revision: Union[str, None] = '295195b72d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('viewed', sa.Boolean(), nullable=False))
    op.alter_column('movies', 'description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'description',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.drop_column('movies', 'viewed')
    # ### end Alembic commands ###
